### ISSUE TITLE
Github Scripts: consider removing display:block from tables in github wikis

### ISSUE THREAD

**Issue by mcking65** [jcsteh/axSGrease#22]
In github wikis, if you create a table in markdown, for instance in a mediawiki page, github renders it with display:block. As a result, the table is not recognized as a table in Firefox or Chrome.

For an example of this, see the [release plans page](https://github.com/w3c/aria-practices/wiki/Release-Plans) in the aria-practices wiki. There is  a table under the heading "Plans by Version and Release". However, it is not readable as a table when using Firefox or Chrome.

I also reported this to github because I do not think it is appropriate to apply display:block to all wiki tables by default. Further, it is debatable whether or browsers should hide the table semantics based on the display:block styling. For instance, see [Firefox bug 1005271](https://bugzilla.mozilla.org/show_bug.cgi?id=1005271).

Until there is some change in Github or in Firefox or Chrome, the only way to read tables in the github wikis is to use IE, which is not really a practical option. So removing or overriding the display:block from the tables would be super helpful!

**Comment by jcsteh** [comment]
There's already a tweak in the script which uses ARIA roles to override
this. Removing display: block; is more risky, since it probably affects the
visual presentation. Obviously, GitHub changed something and that tweak is
no longer applying. That's not surprising - they keep changing the table
stuff - though it is kinda frustrating. :(

**Comment by mcking65** [comment]
hmm, maybe my scripts are back level ... I'll update and retry!

**Comment by mcking65** [comment]
Jamie, it's strange. I updated tamper monkey and made sure the github scripts are up-to-date. Still, the tables in the aria-practices wiki are not getting rendered as tables.

**Comment by jcsteh** [comment]
I believe you. To be clear, there is a tweak in the scripts to deal with
this, but I guess GitHub changed something and that tweak no longer matches
properly, which doesn't surprise me in the slightest. I'll need to figure
out what they changed and adapt accordingly.

**Comment by jcsteh** [comment]
These tables behave fine with latest Firefox and Chrome.
